// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/add-patient" | "/dashboard/add-patient/next" | "/dashboard/audit-logs" | "/dashboard/patients" | "/dashboard/patients/[patientId]" | "/dashboard/patients/[patientId]/edit" | "/dashboard/settings" | "/login"
type AppRouteHandlerRoutes = "/api/audit-logs" | "/api/auth/[...nextauth]" | "/api/health" | "/api/health/ready" | "/api/options" | "/api/patient-tests" | "/api/patients"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/audit-logs": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/health": {}
  "/api/health/ready": {}
  "/api/options": {}
  "/api/patient-tests": {}
  "/api/patients": {}
  "/dashboard": {}
  "/dashboard/add-patient": {}
  "/dashboard/add-patient/next": {}
  "/dashboard/audit-logs": {}
  "/dashboard/patients": {}
  "/dashboard/patients/[patientId]": { "patientId": string; }
  "/dashboard/patients/[patientId]/edit": { "patientId": string; }
  "/dashboard/settings": {}
  "/login": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
